# Generated by Django 3.2 on 2021-04-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_questionone_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.chapter'),
        ),
    ]
