# Generated by Django 3.2 on 2021-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_test_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='file_to_download',
            field=models.FileField(blank=True, null=True, upload_to='chapter_file'),
        ),
    ]
