# Generated by Django 3.2 on 2021-04-20 06:43

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chapter_file_to_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
