# Generated by Django 3.2 on 2021-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='marks',
            field=models.PositiveIntegerField(),
        ),
    ]
