# Generated by Django 3.2 on 2021-05-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_essentials', '0003_question_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam',
            new_name='test',
        ),
    ]
