# Generated by Django 3.2 on 2021-05-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_essentials', '0006_alter_news_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='question_number',
        ),
    ]
